#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "incpri"
    echo "  For each prioritized item, increases priority."
    echo ""
    exit
}

for pri; do true; done

for i in $(seq 1 `expr $# - 1`); do
    $TODO_SH command pri ${!i} $pri;
done
