#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
    echo "incpri $prirange"
    echo "  For each prioritized item in the range (eg.: A-C), increases priority."
    echo ""
    exit
}

chr() {
  [ "$1" -lt 256 ] || return 1
  printf "\\$(printf '%03o' "$1")"
}

ord() {
  LC_CTYPE=C printf '%d' "'$1"
}

range="$1"
range=${range^^}

let count=0
while read line; do
    ((count++))
    [[ $line =~ ^\(([$range])\) ]] && oldpri=${BASH_REMATCH[1]}
    oldpriord=`ord $oldpri`
    newpri=`chr $(($oldpriord -1))`
    if [ $oldpri ]
    then
        if [ "$oldpri" != "A" ]
        then
            "$TODO_SH command pri $count $newpri"
        fi
    fi
    oldpri=
done <$TODO_FILE

